### ISSUE TITLE
Updating Responsibility Assignment Matrix (RAM)

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#103]
## Issue Description
Updating the previous RAM with the new one with the new decided project plan.

## Deadline
30.4.2024- 22.00

**Comment by oktayozel** [comment]
@kaanyolcu22 https://github.com/bounswe/bounswe2024group6/wiki/Milestone-1-Project-Plan
can u check?

**Comment by oktayozel** [comment]
@anilanlar can u check and cluse
