### ISSUE TITLE
improvement(backend): asynchronize WikiData API Calls

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#105]
## Issue Description
There are 3 WikiData API calls we are making, and they are synchronous. As the WD API calls take a long time to return a result, we can asynchronize the requests to increase throughput.
## Tasks
- [x] Import necessary libraries (3rd party libraries such as adrf to make asynchronous calls in Django)
- [x] Refactor code so that request calls are asynchronous

## Estimated Time

**Estimated Time:** 1.5 hours

## Deadline

**Deadline:** 30/4/2024 15.00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 30/4/2024 18.00

**Comment by kaanyolcu22** [comment]
Solved ,with pr #107
