### ISSUE TITLE
Project Plan Update

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#112]
## Tasks

- [x] Update Tasks Table
- [x] Update Textual Parts 
- [x] RAM Matrix

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 30/04/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @oktayozel @kaanyolcu22 @Elifnurdeniz 
**Review Deadline:** 30/04/2024 - 22:00

**Comment by kaanyolcu22** [comment]
thanks , Oktay
