### ISSUE TITLE
Writing README

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#118]
## Issue Description
write a general README.md for building the project from the start. 

## Tasks
- [x] Describing our project briefly (Pending)
- [x] Neccessarry guidance and commands for building (Pending)

## Deadline

**Deadline:** 30/04/2024-22.00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 @yunusemreozdemir 
**Review Deadline:** 30/04/2024-22.00

**Comment by Elifnurdeniz** [comment]
I'm done with the general setup and web part. Also, added the current project status. Anıl will add mobil part.

**Comment by anilanlar** [comment]
I have updated the readme file in a way that describes how to initialize the react native app.

**Comment by anilanlar** [comment]
@yunusemreozdemir Could you check it please?
