### ISSUE TITLE
configuring settings.py and validating via test.rest

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#121]
## Tasks

- [x] settings
- [x] database configuration and connection(sqlite)
- [x] testing

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 30/04/2024 - 22.00

## Reviewer Assignment

**Reviewer:** @Reviewer
**Review Deadline:** DD/MM/YYYY - HH:MM

**Comment by skywllker** [comment]
well done, I am closing the issue
