### ISSUE TITLE
Design Home Page Navbar

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#123]
Design a navigation bar for the application. It should have different features for registered and guest users.

**Comment by yunusemreozdemir** [comment]
I have implemented the Navbar component [here](https://github.com/bounswe/bounswe2024group6/blob/main/frontend/src/components/Navbar.tsx). Related pr is [here](https://github.com/bounswe/bounswe2024group6/pull/95), though further changes were made. Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Looks fine, thanks.
