### ISSUE TITLE
Design Browse Page And Search Bar

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#124]
Design the page for the wikidata search results. Add functionalities to search bars in all pages.

**Comment by Elifnurdeniz** [comment]
Browse page can be seen in [here](https://github.com/bounswe/bounswe2024group6/blob/main/frontend/src/pages/Browse.tsx). Search bar is now functional.

**Comment by yunusemreozdemir** [comment]
Great work.
