### ISSUE TITLE
Design Home Page UI

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#125]
Design the home page that has search part for guest users and sign-in, sign-up parts.

**Comment by yunusemreozdemir** [comment]
I have implemented the Home Page UI [here](https://github.com/bounswe/bounswe2024group6/blob/main/frontend/src/pages/Home.tsx). Related pr is [here](https://github.com/bounswe/bounswe2024group6/pull/95), though further changes were made. Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Looks fine, thanks.
