### ISSUE TITLE
Implement UseAuth Function

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#127]
Create a function to check if the current user is authenticated. Use that function in all pages to determine user authentication.

**Comment by yunusemreozdemir** [comment]
I have implemented useAuth [here](https://github.com/bounswe/bounswe2024group6/blob/main/frontend/src/hooks/useAuth.tsx). Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Looks fine, thanks.
