### ISSUE TITLE
Meeting Notes Update

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#132]
## Issue Description
We need to modify the meeting notes . We had a lot of meetings before the Milestone 2  separately as mobile , web and backend teams  but we did not documented them. 

## Deadline

**Deadline:** 02/05/2024-22.00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir @oktayozel @kaanyolcu22 @battal255 
**Review Deadline:** 02/05/2024-22.00

**Comment by Elifnurdeniz** [comment]
I added meeting notes related to frontend and devops. Reviewers can check.
