### ISSUE TITLE
Docker Compose Fix

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#134]
There seems to be an issue with docker compose that needs to be fixed, it seems like it can't sometimes find vite command.

**Comment by yunusemreozdemir** [comment]
It was related with the installation of node_modules. I have fixed it by mounting an anonymous persistent volume to backend service for node_modules so the local can't override it. This fix can be found in this [pr](https://github.com/bounswe/bounswe2024group6/pull/91). Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Thank you.
