### ISSUE TITLE
Setup the Expo React Native App,

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#138]
## Issue Description
Setup and initialize the expo react native app as a foundation for the searchitect app.

## Tasks
- [x] Initialize the app (Completed)
- [x] Search and find the necessary packages that might be needed in the project (Completed)
- Run the app for the first time. 

## Estimated Time
**Estimated Time:** 2 hours

## Deadline

**Deadline:** DD/MM/YYYY - HH:MM

## Reviewer Assignment
**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 05/05/2024 - 23:59

**Comment by anilanlar** [comment]
@yunusemreozdemir I have set up the mobile app, you can see it [here](https://github.com/bounswe/bounswe2024group6/tree/mobile).

**Comment by yunusemreozdemir** [comment]
Fantastic.
