### ISSUE TITLE
Develop Login Feature for Mobile App

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#139]
## Issue Description
Implement the login feature for Searchitect's mobile app.

## Tasks
- [x] Create and code the UI of login page (Completed)
- [x] Create the http requests for the login functionality (Completed)

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 05/05/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 05/05/2024 - 23:59

**Comment by anilanlar** [comment]
@yunusemreozdemir I have implemented the feature, you can see it [here](https://github.com/bounswe/bounswe2024group6/tree/mobile).

**Comment by yunusemreozdemir** [comment]
Great work, I am closing this issue as we have tested this feature in our presentation.
