### ISSUE TITLE
[Mobile Sign Up]: Create the Sign Up Page for Searchitect's Mobile App

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#140]
## Issue Description
Implement the sign up feature for Searchitect's mobile app.

## Tasks
- [x] Create and code the UI of sign up page (Completed)
- [x] Create the http requests for the sign up functionality (Completed)

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 05/05/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 05/05/2024 - 23:59

**Comment by anilanlar** [comment]
@yunusemreozdemir I have implemented the feature, you can see it [here](https://github.com/bounswe/bounswe2024group6/tree/mobile).

**Comment by yunusemreozdemir** [comment]
Great work, I am closing this issue as we have tested it in our presentation.
