### ISSUE TITLE
[Search Functionality]: Implement Search Functionality in the Landing Page

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#141]
## Issue Description
Implement the search feature for Searchitect's mobile app.

## Tasks
- [x] Create and code the UI of landing page (Completed)
- [x] Create the http requests for the search functionality (Completed)

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 05/05/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 05/05/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
Nice job Anıl.
