### ISSUE TITLE
Design and Implement Database Models

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#142]
## Issue Description
For our project we need to determine what models will have our database determine their relations . We will do it by the help of Class Diagrams [here](https://github.com/bounswe/bounswe2024group6/wiki/Class-Diagrams) designed before. After the design part we need to implement these models and migrate them.

## Tasks

- [x] Design Entity Models (Pending)
- [x] Implement Models (Pending)

## Estimated Time

**Estimated Time:**1 week

## Deadline

**Deadline:** 07/05/2024-23.59

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir @Elifnurdeniz 
**Review Deadline:** 08/05/2024-23.59

**Comment by oktayozel** [comment]
thank you kaan
