### ISSUE TITLE
Milestone Report 2 - Frontend

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#145]
## Issue Description
Parts of reports about the frontend must be written.

## Deadline

**Deadline:** 03/05/2024 20.00

## Reviewer Assignment

**Reviewer:** @arastasci   
**Review Deadline:** 03/05/2024 21.00

**Comment by Elifnurdeniz** [comment]
I and Yunus Emre are done with frontend parts. It is added to Hackmd link. It will appear in [milestone report](https://github.com/bounswe/bounswe2024group6/wiki/Milestone-2-Report) after everyone is done.

**Comment by arastasci** [comment]
looks nice, @Elifnurdeniz - closing the issue.
