### ISSUE TITLE
Milestone Report 2 - Mobile

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#146]
## Issue Description
Parts of reports about the mobile must be written.

## Deadline

**Deadline:** 03/05/2024 20.00

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 03/05/2024 21.00

**Comment by anilanlar** [comment]
Apparently this issue has escaped from notice. I have completed the mobile part of Milestone 2 report, it can be found [here](https://hackmd.io/XSUxeOxbRsG2LKmuStoooQ?view)

**Comment by arastasci** [comment]
i forgor 💀
