### ISSUE TITLE
organize README.md 

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#15]
At the meeting, we talked about how to re-structure the README. Now's the time to do it @eymenesad!
You can find details are at the meeting notes, but here they are:
- add links to personal wikis and home page wiki etc.
- no `:` at headers

**Comment by eymenesad** [comment]
Completed the tast. Can you chech @arastasci @kaanyolcu22

**Comment by arastasci** [comment]
hey eymen, it looks fine and just as we talked, thanks. lets just all keep in mind that after everyone does their personal wiki page, we'll have to update the README again.
