### ISSUE TITLE
create my personal wiki page: Yunus Emre Özdemir

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#17]
I will create my personal wiki page according to the structure defined in the meeting.

**Comment by kaanyolcu22** [comment]
@yunusemreozdemir can you finish it within this week ?

**Comment by yunusemreozdemir** [comment]
I will finish within this week.

**Comment by yunusemreozdemir** [comment]
I have completed [my personal wiki page](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Effort:-Yunus-Emre-Özdemir), can you check @kaanyolcu22 ?

**Comment by kaanyolcu22** [comment]
Thanks @yunusemreozdemir  I am closing the issue
