### ISSUE TITLE
improvement(backend): speed up building wiki endpoint

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#174]
## Issue Description

The building wiki endpoint used multiple SPARQL queries to get related information. We can use a complex query to get all information at once.

## Estimated Time

**Estimated Time:** 1.5 hours

## Deadline

**Deadline:** 16/05/2024 16.00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 16/05/2024 17.00

**Comment by arastasci** [comment]
can anyone check PR #175?

**Comment by kaanyolcu22** [comment]
thanks @arastasci
