### ISSUE TITLE
Backend: Speed up the search query

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#176]
## Issue Description

The search query takes too long and that makes it a frustrating user experience - so we need to speed that up with a more effective query.

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 16/05/2024 18.00

**Comment by arastasci** [comment]
done it, @kaanyolcu22 can you take a look?

**Comment by kaanyolcu22** [comment]
thanks @arastasci
