### ISSUE TITLE
recreating personal wiki page

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#18]
We decided on a new page organisation and some changes needs to be done on the page. Such as adding an about me part.

**Comment by Elifnurdeniz** [comment]
@kaanyolcu22 hey, im done with the page. Can you check?

**Comment by kaanyolcu22** [comment]
I' have done with my page also .

**Comment by kaanyolcu22** [comment]
@Elifnurdeniz  I have checked thanks, I am closing the issue
