### ISSUE TITLE
Advance in Git and Explore and Mention Your Favorite Repositories

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#2]
* Explore GitHub to discover some repositories that you like. Document at least one of them
by providing a reference to the repo and describing what you liked about it.

* Study git as a version management system

**Suggested tutorial:**

https://youtu.be/1ffBJ4sVUb4

Assignees:
- [x] Aras Tasci
- [x]  Yunus Emre Ozdemir
- [ ] Anil Kose
- [x] Oktay Ozel
- [x] Elif Nur Deniz
- [x] Kaan Yolcu
- [x] Halil Ozkan
- [x] Eymen Celikturk
- [x] Battal Hazar
- [ ] Ebru Ozcaki

**Comment by oktayozel** [comment]
I studied git and documented about Turkish Bert Repository in the allocated page.

**Comment by skywllker** [comment]
I researched about ccxt repository and add it into the relevant wiki page

**Comment by arastasci** [comment]
I added my favourite repo to the page

**Comment by kaanyolcu22** [comment]
I have been documented my favorite repo to the page

**Comment by eymenesad** [comment]
I added my favourite repo

**Comment by yunusemreozdemir** [comment]
I studied git and documented about Transformers repository in the Personal Favourite Repositories page.

**Comment by battal255** [comment]
I added one of my favourite repo about chess.

**Comment by Elifnurdeniz** [comment]
As most of the people have done the task and we have changed the styling of the page, I am closing the issue as not to clutter the issues page. @ebru and @anilanlar can open a new issue for the task.
