### ISSUE TITLE
update fav repository: Yunus Emre Özdemir

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#20]
I will create my personal favourite repository according to the structure defined in the meeting.

**Comment by Elifnurdeniz** [comment]
Can you finish it with the tasks of this week?

**Comment by yunusemreozdemir** [comment]
Yes, I will finish it this week.

**Comment by yunusemreozdemir** [comment]
I think my repository description is descriptive enough and contains the necessary information, so I just broke it down to bullet points as we have talked in the meeting. Can you check @Elifnurdeniz ?
