### ISSUE TITLE
Create signup and signup functionalities 

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#206]
## Issue Description

Create signup and signup functionalities. Add a html file also to check if signup is working

## Tasks

- [x] signup view
- [x] user model
- [x] signup urls
- [x] test signup

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by oktayozel** [comment]
@Elifnurdeniz can you check and close
(https://github.com/bounswe/bounswe2024group6/commit/8bc0167d4cca4ad1f44a85d3e2b6bacc8225f719)

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
