### ISSUE TITLE
User homepage and loging

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#207]
## Issue Description

added user homepage and directs to user homepage after logging in
add user homepage and direct to user homepage after logging in. implement login logic.

## Tasks

- [x] html files
- [x] views
- [x] urls
## Estimated Time

**Estimated Time:** 1 hours

## Deadline

**Deadline:** 16/05/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 17/05/2024 - 09:00

**Comment by oktayozel** [comment]
this feature has been changed afterwards.

**Comment by oktayozel** [comment]
@Elifnurdeniz  can you check and close
https://github.com/bounswe/bounswe2024group6/commit/72918e202470cf815e705367122b209df0bc0f4f

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
