### ISSUE TITLE
Add Like Models

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#208]
## Issue Description

Add like model to models.py and implement related features to other files too
## Tasks

- [x] implement like model
- [x] add likes count etc. to other models.
- [ ] 
## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by oktayozel** [comment]
@Elifnurdeniz can you check and close
[added likes to models](https://github.com/bounswe/bounswe2024group6/commit/ae608e5aed8bb7203f76181a50e7ebe0c2040b1e)

**Comment by kaanyolcu22** [comment]
I think this issue is close related to this [issue](https://github.com/bounswe/bounswe2024group6/issues/142)
