### ISSUE TITLE
add serializers for likes and userprofile. add userprofile view and models

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#209]
## Issue Description

Add serializers for likes and userprofile. Add userprofile view and models. Do migrations amd make sure other things are working properly after this update

## Tasks

- [x] like serializer
- [x] userprofile serializer
- [x] userprofile model
- [x] userprofile view
- [x] testing
## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by oktayozel** [comment]
@Elifnurdeniz can you check and close 
https://github.com/bounswe/bounswe2024group6/commit/8bf7ac8cf2d035c097b8a9127b8684edfcd131ab

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
