### ISSUE TITLE
create a wiki home page banner

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#21]
We will design a banner for the wiki home page to give a warmer welcome.

**Comment by oktayozel** [comment]
Can you delete this issue because we have a very similar one [here](https://github.com/bounswe/bounswe2024group6/issues/42)

**Comment by yunusemreozdemir** [comment]
I can't delete this issue since I don't have admin permissions in the repository. Let's close this one along with the other one when the banner is created.

**Comment by oktayozel** [comment]
oh, okay thanks for info

**Comment by oktayozel** [comment]
This issue is also closed along with [this issue](https://github.com/bounswe/bounswe2024group6/issues/42).
