### ISSUE TITLE
bookmark, views, models and database connections, endpoints and testing

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#212]
## Issue Description

create bookmark views, bookmark models and make database connections. Also create endpoints. Test if the functionality of all code is effected

## Tasks

- [ ] bookmark views
- [ ] bookmark models 
- [ ] make database connections
- [ ] create endpoints
- [ ] testing
## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
