### ISSUE TITLE
Update user serializer. Update user profile. Update CustomUser model

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#213]
## Issue Description

Update user serializer. Update user profile. Solve conflicts. Update urls. Update user models accordingly.

## Tasks

- [ ] User serializer
- [ ] user profile
- [ ] Update urls
- [ ] User model
- [ ] test and solve conflicts 

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
