### ISSUE TITLE
unit test for login and signup

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#217]
## Issue Description

write unit tests for login and signup views.

## Tasks

- [ ] login
- [ ] signup
## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
