### ISSUE TITLE
test get posts by id

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#218]
## Issue Description

test get posts by id

## Tasks

- [ ] test get posts by id

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
