### ISSUE TITLE
test user_profile

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#219]
## Issue Description

test user_profile

## Tasks

- [ ]  test user_profile

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
