### ISSUE TITLE
[Mobile Release]: Generate an APK Output

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#257]
## Issue Description

Generate an APK Output for the android users to download the app.

## Tasks

- Get an understanding of APK, build an APK output of the application. 

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 17/05/2024 22:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir @arastasci @oktayozel 
**Review Deadline:** 19/05/2024 - 11.59

**Comment by oktayozel** [comment]
Thank you kaan
