### ISSUE TITLE
Add personal page links to wiki page for Halil Ozkan

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#26]
After creating my personal page, adding it's link to relevant places on the main wiki page

**Comment by skywllker** [comment]
I have done it. One who check can close the issue

**Comment by uskudarli** [comment]
Where is the link?

**Comment by skywllker** [comment]
You can see the link in wiki home page and side bar. I have placed it under my name at side bar and under Personal Wiki & Effort at home page, near my name. the link is: 
https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Effort:-Halil-Özkan

**Comment by uskudarli** [comment]
My point was to always close issues with info about the work. With links
whenever possible

**Comment by skywllker** [comment]
Thanks for the contribution, I will be careful about it.

**Comment by kaanyolcu22** [comment]
@skywllker thanks I am closing the issue
