### ISSUE TITLE
[Issue Title]: Organizing Wiki Sidebar

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#260]
## Issue Description

Organizing wiki sidebar because we are starting a new project. 

## Tasks

- [ ] Organize wiki sidebar (Pending)

## Deadline

**Deadline:** 24/09/2024 

## Reviewer Assignment

**Reviewer:** @skywllker
**Review Deadline:** 24/09/2024

**Comment by Elifnurdeniz** [comment]
I'm done. Can you check @skywllker ?

**Comment by skywllker** [comment]
Controlled it, looks great
