### ISSUE TITLE
Creating new Personal Pages for Newcomers

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#261]
## Issue Description
Welcome to Group 6! Newcomers shall create their own personal pages.

## Tasks

- [x] Ahmet Oguz Engin 
- [x] Yagız Güldal  
- [x] Ali Tarık Şahin

## Estimated Time

**Estimated Time:** 1 hour

## Reviewer Assignment

**Reviewer:** @kaanyolcu22

**Comment by aoengin** [comment]
Created wiki pages for myself and Yagiz;
[Personal Wiki & Efforts: Ahmet Oğuz Engin](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Efforts:-Ahmet-Oğuz-Engin)
[Personal Wiki & Efforts: Yağız Güldal](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Efforts:-Yağız-Güldal)

Also created an empty page for Ali Tarik Şahin;
[Personal Wiki & Efforts: Ali Tarik Şahin](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Efforts:-Ali-Tarik-Şahin)

**Comment by aoengin** [comment]
@kaanyolcu22 Can you review the personal pages and close the issue if everything is okay?

**Comment by kaanyolcu22** [comment]
Thanks , it is okay.
