### ISSUE TITLE
[Issue Title]: Organizing homepage

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#263]
## Issue Description

Organizing homepage for our new project

## Tasks

- [ ] Organizing homepage

## Deadline

**Deadline:** 24/09/2024

## Reviewer Assignment

**Reviewer:** @skywllker 
**Review Deadline:** 24/09/2024

**Comment by arastasci** [comment]
I organized the home page, can you check [it](github.com/bounswe2024group6/wiki) @skywllker ?
