### ISSUE TITLE
Lab Report 1: 24 September 2024

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#265]
## Issue Description

Write the Lab Report 1
## Tasks

Talk to everyone and gather what are done in the lab in that report.

## Estimated Time

1h

## Deadline

24 Sep 2024 20.00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz

**Comment by oktayozel** [comment]
@Elifnurdeniz here you can find the lab report:

https://github.com/bounswe/bounswe2024group6/wiki/Lab-Report-1

**Comment by YavizGuldalf** [comment]
Shouldn't we close this issue, isn't it completed? @oktayozel, @Elifnurdeniz

**Comment by Elifnurdeniz** [comment]
Sorry for the delay. I'm closing it.
