### ISSUE TITLE
Creating A Lab Report Template

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#266]
## Issue Description

Create a lab report template for simplicity. 

## Tasks

- [x] Create report template

## Estimated Time

**Estimated Time:** 20 minutes

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz

**Comment by YavizGuldalf** [comment]
I have created an initial version of the document under the name Lab-Report-Template, you can find it [here](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Report-Template). I have also taken the liberty to add it to the sidebar, so you can check that out as well.

**Comment by Elifnurdeniz** [comment]
It looks great, thanks.
