### ISSUE TITLE
[Requirements]: Creating a Glossary

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#268]
## Issue Description
The project lacks a glossary for defining key terms, resulting in potential user confusion. A glossary is required to enhance clarity and understanding.

## Tasks
- [x] Create a glossary 

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 30/09/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @arastasci 
**Review Deadline:** 01/10/2024 - 13:00

**Comment by aoengin** [comment]
Created the requirements page and Glossary section. @arastasci  Please check the related [revision](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-CmpE451/428b0ea9fb75ba5e4b4df52f82ecba39ff6ab677).

**Comment by arastasci** [comment]
Looks fine, closing the issue.
