### ISSUE TITLE
Requirements: Preliminary Functional Requirements

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#269]
## Issue Description
We want to create a preliminary requirements document before the second week's lab. Since the lab lasts for only two hours and our TA is responsible for 5 other groups, we have a very small window to talk about our project's details. That's why we want to come to the lab prepared with a preliminary _Requirements_ document already prepared. 

This issue is one of the prerequisites for the aforementioned task, as the _functional requirements_ is one of the key parts to identify in order to determine  all requirements. 

This issue should be completed before the start of next week's lab, but it'd be wise to have it completed before then to leave some time for a good review.

## Tasks

- [x] Create a requirements document (if it doesn't already exist)
- [x] Fill in the functional requirements according to your vision of the project

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 01/10/2024 - 13:00

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 01/10/2024 - 15:00

**Comment by aoengin** [comment]
The [requirements page](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-CmpE451) has been created, and a section for "Registration and Login-Logout Requirements" has been added.

**Comment by aoengin** [comment]
I've appended three new sections: 'Guest User Requirements,' 'Registered User Requirements,' and 'Account Requirements.' We will likely need to make further additions and updates to these sections. Please see the [revision](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-CmpE451/0a113d53fcb21f6fa48075fae5d86ccae1caf64f).

**Comment by oktayozel** [comment]
I have added further requirements [link](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-CmpE451) (system, and non-functionals). I am going to make additions to system requirements.

**Comment by Elifnurdeniz** [comment]
I have changed a few requirement that we are not certain to implement from 'shall' to 'should' (recovery email parts). I have added the quiz requirements part and made some additions to other functional requirements.

**Comment by arastasci** [comment]
The preliminary requirements can be considered complete, we'll update it based on the discussion we had in the lab meeting and according to the answers of elicitation questions.
