### ISSUE TITLE
Lab Report: 1st of October 2024

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#274]
## Issue Description
This week's lab meeting will focus on choosing a W3C standard and presenting the TA with our requirements draft as well as our elicitation questions. We'll need to write down the results to a wiki article. 

## Tasks

- [x] Write a lab report using the [lab report template](https://github.com/bounswe/bounswe2024group6/wiki//Lab-Report-Template)

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 01/10/2024 - 19:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf
**Review Deadline:** 02/10/2024 - 20:00

**Comment by aoengin** [comment]
[Lab report](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Report-2/40fe6362907712d8643493164499670436443e3e) is created.
