### ISSUE TITLE
Take Meeting 2 Notes

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#276]
## Tasks

Take notes and keep track of them

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

Deadline: Oct 1 
## Reviewer Assignment

**Reviewer:** @aoengin

**Comment by oktayozel** [comment]
[Link](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-2) @aoengin can you please review it

**Comment by aoengin** [comment]
> [Link](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-2) @aoengin can you please review it

Can you please add a section for actions items?

**Comment by aoengin** [comment]
LGTM
