### ISSUE TITLE
Filling Elicitation Questions Answers

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#278]
## Issue Description
After the meeting with the customer, answers to elicitation questions must be filled based on the notes.

## Tasks

- [x] Fill the answers

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 01/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir

**Comment by Elifnurdeniz** [comment]
I have filled the answers [here](https://github.com/bounswe/bounswe2024group6/wiki/Elicitation-Questions-CMPE-451). I also added the extra questions that we asked. Can you check @yunusemreozdemir ?

**Comment by yunusemreozdemir** [comment]
Great work!
