### ISSUE TITLE
Use Case Diagram: First Version

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#279]
## Issue Description
In order to move forward with our software designs, we need to first prepare a few diagrams to make sure everyone in the team is on the same page. The UML Use Case Diagram for our app is the first of these diagrams. It should show the different actors that the app is intended for and show the possible use cases for each actor. It should be a high level diagram focusing on the general use cases rather than detailing every single option.

## Tasks

- [x] Create a use-case diagram.
- [x] Create a small wiki article explaining the use-case diagram.

## Estimated Time

**Estimated Time:** 90 minutes

## Deadline

**Deadline:** 05/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @oktayozel 
**Review Deadline:** 05/10/2024 - 12:00

**Comment by YavizGuldalf** [comment]
@skywllker I have created a draft of the use case diagram below. Do you think it needs any changes? If you think it's fine, can you create a small wiki article explaining the use case diagram?
![CMPE 451 Use Case Diagram drawio](https://github.com/user-attachments/assets/3c0bacc9-2255-43d4-9cd8-bc6bdc6e650d)

**Comment by skywllker** [comment]
I added it to our GitHub wiki page, under 451 Project with explanations.

**Comment by YavizGuldalf** [comment]
Upon @aoengin's request, I have changed the use case diagrams. @aoengin do you wish to add anything else?

![CMPE 451 Use Case Diagram-Page-1 drawio](https://github.com/user-attachments/assets/3a65a634-7632-4bd4-aea4-df8342473893)

**Comment by YavizGuldalf** [comment]
Apparently this is still missing bookmarking/favoriting functionality for quizzes and forum threads/post, I'll add them the first chance I get.

**Comment by YavizGuldalf** [comment]
Here's the final version.
![CMPE 451 Use Case Diagram-Page-1 drawio-3](https://github.com/user-attachments/assets/04979b25-395d-4bff-97ed-1c19b18485da)

**Comment by YavizGuldalf** [comment]
We can close this issue and continue over at #286 if it's okay with you @oktayozel.

**Comment by oktayozel** [comment]
Thank you @YavizGuldalf
