### ISSUE TITLE
Responsibility Assignment Matrix Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#28]
A research on Responsibility Assignment Matrix will be done and documented on the research section of the wiki by this week.

**Comment by oktayozel** [comment]
@Elifnurdeniz hello, I have completed my tentative research. You can see it [here](https://github.com/bounswe/bounswe2024group6/wiki/Responsibility-Assignment-Matrix(RAM)-%E2%80%90-RESEARCH). Can you check it when you have time. Thank you:)

**Comment by Elifnurdeniz** [comment]
Can you put it on the domain analysis page? The research documentation looks fine.
