### ISSUE TITLE
[Meeting Notes]: Weekly Meeting 2

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#280]
## Issue Description
A new wiki article must be created under the Meeting Notes section in accordance with our Meeting Notes template for the Weekly Meeting 2 (Sunday, 6th of October 2024, 13:00).

## Tasks
- [x] Create a Meeting Notes wiki article for this meeting

## Estimated Time
Estimated Time: 30 minutes

## Deadline
Deadline: 06/10/2024 - 18:00

## Reviewer Assignment
Reviewer: @YavizGuldalf

**Comment by aoengin** [comment]
[Meeting notes](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-Weekly-Meeting-2/4f580c6aebd3687543aa2bdca28613152785c114) for weekly meeting 2 is created. @YavizGuldalf

**Comment by YavizGuldalf** [comment]
LGTM!
