### ISSUE TITLE
[Design]: Front-End Mockups - First Version

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#282]
## Issue Description
Front-end mockups will be created to show how the user interface should look when it's built. These mockups will help make sure everyone agrees on the design before starting development.

## Tasks
- [x] Create the first version of front-end mockups

## Estimated Time
**Estimated Time:** 5-6 hours

## Deadline
**Deadline:** 10/10/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @skywllker 
**Review Deadline:** 11/10/2024 - 23:59

**Comment by alitariksahin** [comment]
[First Drafts](https://github.com/bounswe/bounswe2024group6/wiki/Front%E2%80%90End-Mockups-First-Drafts)

**Comment by Elifnurdeniz** [comment]
I added the profile pages and login-register page. I reviewed the rest of the mockups and compared them all with mobile mockups. After review we can add the draft to wiki.

**Comment by Elifnurdeniz** [comment]
I edited the pages after comparing them with the mobile for the last time. I added all the pages except quiz creation to [wiki](https://github.com/bounswe/bounswe2024group6/wiki/Front%E2%80%90End-Mockups-First-Drafts).

**Comment by alitariksahin** [comment]
@skywllker can you review, we are done with the frontend mockups

**Comment by skywllker** [comment]
great job
