### ISSUE TITLE
[Diagrams]: Class Diagrams

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#283]
## Estimated Time

5 hours
## Deadline

**Deadline:** 12/10/2024 

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 13/10/2024

**Comment by YavizGuldalf** [comment]
How's this issue coming along guys? This issue supposed to be done at this point, but I cannot find a related wiki article in the wiki. Can you please fill that in and close the issue if it's finished. We need the class diagrams ready to check if there are any inconsistencies between it and the sequence diagrams in #297.

**Comment by arastasci** [comment]
well, seems like we forgot to make a wiki page for it, this issue was completed long ago and we had the diagrams ready. @kaanyolcu22 can you check the related page? [here](https://github.com/bounswe/bounswe2024group6/wiki/Class-Diagrams) it is.

**Comment by kaanyolcu22** [comment]
Thanks , Aras.

**Comment by oktayozel** [comment]
@kaanyolcu22 ?
