### ISSUE TITLE
Create a Project Plan

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#285]
## Issue Description
We should create a project plan that will span the whole development. Although two people are assigned, we'll get the opinion of the whole team.

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 10/10/2024 22:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 11/10/2024 22:00

**Comment by kaanyolcu22** [comment]
We have created a simple project plan until the milestone 1 for know with @arastasci . Can you check if it is okay @yunusemreozdemir ?
![WhatsApp Image 2024-10-13 at 19 46 17](https://github.com/user-attachments/assets/0e981bb9-52f2-4e95-8dcf-85d0334c4bc9)
![WhatsApp Image 2024-10-13 at 19 46 24](https://github.com/user-attachments/assets/0e9620a5-d9c0-444c-8200-028b6bce014c)

**Comment by arastasci** [comment]
Upon team's collaborative review, we have revised the project plan until Milestone 1, and will create the remaining plan in the near future, can you check @yunusemreozdemir?
![image](https://github.com/user-attachments/assets/3546a381-f4db-41fe-8b55-2d535491b43b)
![image](https://github.com/user-attachments/assets/1ac101e5-710e-4ef9-b6ab-fdb654bce35d)

**Comment by YavizGuldalf** [comment]
Sorry, I accidentally closed this issue, I am now reopening it.

**Comment by kaanyolcu22** [comment]
@YavizGuldalf @yunusemreozdemir  Here is the outline of the [Project Plan](https://sharing.clickup.com/9018594707/g/h/8crtnck-338/c21046f71e93555) as gantt chart until the Milestone 3. Can you check If it is enough ? And inform me if something missing or wrong .

**Comment by YavizGuldalf** [comment]
It looks decent. For mobile, we will have to implement many of the pages related to quizzes for the 1st customer milestone, but they won't be the final versions. So I don't think having them further down the line in the gantt chart is a problem.

**Comment by arastasci** [comment]
We have put together the complete project plan in [this](https://github.com/bounswe/bounswe2024group6/wiki/General-Project-Plan) wiki page. We got positive feedback from @YavizGuldalf - can you check it as well @yunusemreozdemir  (as the reviewer)?
