### ISSUE TITLE
Update Requirements and Preliminary Use Case Diagram

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#286]
## Issue Description

Update the requirements and preliminary use case diagram according to the discussions we had the feedbacks we got in the lab session - see meeting notes for the updates.
## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 10/10/2024 22:00

## Reviewer Assignment

**Reviewer:** @aoengin 
**Review Deadline:** 11/10/2024 22:00

**Comment by YavizGuldalf** [comment]
I think the following version can be final for the use case diagram, what do you think @aoengin?
![CMPE 451 Use Case Diagram-Page-1 drawio](https://github.com/user-attachments/assets/7c5042b5-9ba9-4750-ad9d-2c25ff5918f5)

**Comment by aoengin** [comment]
The requirements section has already been updated, and the use case diagrams look perfect! Great job. @YavizGuldalf
