### ISSUE TITLE
Host Lab Meeting 3 

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#287]
## Issue Description

Take meeting notes and create and assign issues according to outcomes.

# Reviewer Assignment
**Reviewer:** @kaanyolcu22

**Comment by arastasci** [comment]
Done - see the [meeting notes](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-3). @kaanyolcu22

**Comment by kaanyolcu22** [comment]
I , checked thanks Aras
