### ISSUE TITLE
[Requirements]: Finalize Requirements

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#289]
## Issue Description
Requirements should be finalised by grouping parallel to the use case diagram and bullet points should de be converted to the numbers for easy referral.

## Tasks
- [x] Convert bullet points to the numbers
- [x] Regroup the elements

## Estimated Time
**Estimated Time:** 50 mins

## Deadline
**Deadline:** 8/10/2024 - 19:50

## Reviewer Assignment
**Reviewer:** @arastasci   
**Review Deadline:** 8/10/2024 - 20:00

**Comment by aoengin** [comment]
[Requirements](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-451) have been finalised.

**Comment by arastasci** [comment]
LGTM.
