### ISSUE TITLE
Wikidata and Wikidata API Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#29]
A research on Wikidata and Wikidata API will be done and documented on the research section of the wiki by this week.

**Comment by anilanlar** [comment]
Finished my research. Started documenting it [here](https://github.com/bounswe/bounswe2024group6/wiki/Wikidata-and-Wikidata-API). I have not finished documentation yet.

**Comment by Elifnurdeniz** [comment]
Can you do the documentation on [this](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis) page?

**Comment by anilanlar** [comment]
Sure, my research can be found the [here](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis).
