### ISSUE TITLE
[Mockups]: Mobile Mockups

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#290]
## Issue Description
We need to create reasonable UI mock-ups for mobile part of the app.

## Tasks

- [x] Create mock-ups for mobile pages, referring to the requirements and other diagrams.

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 10/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar  
**Review Deadline:** 11/10/2024 -23:59

**Comment by YavizGuldalf** [comment]
Unfortunately, the diagram has gotten too big (> 1M) and thus excalidraw does not let me save it to the cloud. Here is a google drive link to the latest version of the file, you can both view and edit this file.

https://drive.google.com/file/d/1xshwlrnt6A8Pwo946_FZgWUQ5Uq-Orbp/view?usp=share_link

**Comment by YavizGuldalf** [comment]
I think I have added all that I want to the Mobile Mockups, you can download the file [here](https://drive.google.com/file/d/1xshwlrnt6A8Pwo946_FZgWUQ5Uq-Orbp/view?usp=sharing) and view and edit it using [excalidraw](https://excalidraw.com). I tried to include every use-case found in the use-case diagram in the mock-ups.@anilanlar, @aoengin could you please check the file for any issues? Because I don't have any experience designing mobile UIs, there is probably room for a lot of improvement in that front.

**Comment by YavizGuldalf** [comment]
After reviewing the sequence diagrams and front-end mockups, I have noticed a few things missing from the mobile mockups, I'll probably add them later tonight:
* Log-in and registration should use email instead of username.
* Username should be modifiable (though this seems counterintuitive to me, maybe we should talk with the front-end team)
* There is no such thing as a nickname (the initial thought was that username was private and used to log in while nickname was the name shown to others, but email-username is better imo)
* Adding/removing tags from own post.
* Quiz creation pages are missing
* Post creation pages are missing.

**Comment by aoengin** [comment]
I've made the changes you've mentioned. Please check the last version of [mockups](https://drive.google.com/file/d/1lWRUTLg_fGqOh-QfMm0ptbCg3XA5j0kZ/view?usp=share_link). 
We need to add real contents to the posts. @YavizGuldalf

**Comment by YavizGuldalf** [comment]
I have added real content to the posts. I have also added a few buttons that I thought were missing, like the question type selection buttons while creating a question and the tag remove/add buttons while editing the tags of a quiz (though I left it grayed out for the level tag as I don't think it should be removable). You can find my latest additions [here](https://drive.google.com/file/d/1hT0lHu3QAungLIWecRhsHVbtG6-yxMze/view?usp=sharing).

**Comment by YavizGuldalf** [comment]
I think we are pretty much done with this issue, what do you think @aoengin, @anilanlar?

**Comment by aoengin** [comment]
@YavizGuldalf I've already made the necessary updates. We're done unless there's an update from the front-end team.

**Comment by anilanlar** [comment]
@YavizGuldalf, @aoengin The mockup design seems quite detailed and synced with front-end mockup so far. Congrats for your meticulous work.

**Comment by aoengin** [comment]
A [wiki page ](https://github.com/bounswe/bounswe2024group6/wiki/Mobile-Mockups) is created for mobile mockups.
