### ISSUE TITLE
[Templates]: Add Agenda Section to the Meeting Notes Template

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#291]
## Issue Description
Add an "Agenda" section to the existing meeting notes template to ensure key topics are organized and covered in each meeting. This will improve structure and clarity, helping participants stay aligned on discussion points.

## Tasks
- [ ] Add "Agenda" section to the existing meeting notes template

## Estimated Time
**Estimated Time:** 5 mins

## Deadline
**Deadline:** 12/10/2024 - 17:00

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 12/10/2024 - 18:00

**Comment by aoengin** [comment]
[Agenda section](https://github.com/bounswe/bounswe2024group6/wiki/Meeting-Notes-Template/c569c9bde18c2cb53e38c3e795ec3d120c1f156b) has been added to the existing meeting notes template.

@YavizGuldalf

**Comment by YavizGuldalf** [comment]
Looks good!
