### ISSUE TITLE
Improvements For The Project

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#292]
## Issue Description
This issue is for additional ideas that can enhance the learning experience of the app. Everybody can comment their ideas under this issue. 

## Tasks

- [x] Adding ideas

## Deadline

**Deadline:** 15/10/2024 - 15:00

**Comment by Elifnurdeniz** [comment]
The team came up with the idea of adding a "word of the day" feature. It will be further discussed in the next lab.

**Comment by YavizGuldalf** [comment]
We can create a system where it's possible for users to mention quizzes and questions from within the forums. This way, people can discover quizzes that may be of interest to them in the forums and directly go to those quizzes.

**Comment by alitariksahin** [comment]
We can consider utilizing the questions users answered wrong.
This could be done by asking these questions later, or creating another quiz for such questions

**Comment by Elifnurdeniz** [comment]
We can close this issue right now and have another discussion while reviewing milestone 1.
