### ISSUE TITLE
Create Personal Effort Page in Wiki

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#3]
Everyone will create a personal effort page for their own efforts, and note down their efforts **weekly**. 

The weekly effort template must be followed.

Assignees:
- [x] Aras Tasci
- [x]  Yunus Emre Ozdemir
- [x] Anil Kose
- [x] Oktay Ozel
- [x] Elif Nur Deniz
- [x] Kaan Yolcu
- [x] Halil Ozkan
- [x] Eymen Celikturk
- [x] Battal Hazar
- [ ] Ebru Ozcaki

**Comment by oktayozel** [comment]
I did my own page: [link](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort-(Oktay-%C3%96zel))

**Comment by Elifnurdeniz** [comment]
I created my own page here[https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort-(Elif-Nur-Deniz)](url)

**Comment by battal255** [comment]
I create my effort page  [here](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort-(Battal-HAZAR))

**Comment by skywllker** [comment]
I made my own effort page

**Comment by arastasci** [comment]
I also did, it's [here](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort-(Aras-Taşçı))

**Comment by eymenesad** [comment]
I created my effort page [here](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort-(Eymen-Çeliktürk))

**Comment by yunusemreozdemir** [comment]
I created my effort page [here](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Effort:-Yunus-Emre-Özdemir)

**Comment by kaanyolcu22** [comment]
As most of the people have done the task and we have changed the styling of the page, I am closing the issue as not to clutter the issues page. @Ebru can open a new issue for the task.
