### ISSUE TITLE
Linked Data and SPARQL Semantic Queries Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#30]
A research on Linked Data and SPARQL semantic queries will be done and documented on the research section of the wiki by this week.

**Comment by yunusemreozdemir** [comment]
We documented our research on Linked Data and SPARQL Semantic Queries on the [Domain Analysis](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis) page under the Research section of the wiki.
Can you check @Elifnurdeniz ?
