### ISSUE TITLE
Mobile - Integrate quiz view API endpoint 

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#304]
## Issue Description
Integrating the quiz view functionality until milestone 1 with mockdata provided by backend.

## Deadline

**Deadline:** 21/10/2024 - 14:00

## Reviewer Assignment

**Reviewer:** @aoengin 
**Review Deadline:** 21/10/2024 - 20:00

**Comment by aoengin** [comment]
We were not able to integrate yet. We'll be working on this issue later.
