### ISSUE TITLE
Mobile - Quiz Creation Page

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#305]
## Issue Description
Creating the quiz creation pages similar to mobile mock ups designed before.

## Deadline

**Deadline:**  21/10/2024- 14:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:**  21/10/2024- 20:00

**Comment by YavizGuldalf** [comment]
This is completed with #365, good job @anilanlar.
