### ISSUE TITLE
Frontend - Creating Forum Page

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#306]
## Issue Description
Creating Forum Page that we can show the customer basic post page that users interacts and shares their ideas about any related topic .

## Deadline

**Deadline:** 21/10/2024 - 14:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:**  21/10/2024 - 20:00

**Comment by Elifnurdeniz** [comment]
We divided tasks between us. We can close this issue @yunusemreozdemir.
