### ISSUE TITLE
Frontend - Integrating Create Post Endpoint

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#307]
## Issue Description
The users should be able to add posts on the forum page . We should show this functionality to the customer for milestone 1.

## Deadline

**Deadline:** 21/10/2024-14:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 21/10/2024-20:00

**Comment by Elifnurdeniz** [comment]
We are done with the changes for the first milestone. All functionalities are available at [here](http://161.35.208.249:5173/forum).
