### ISSUE TITLE
Mobile Application Development Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#31]
A research on Mobile application development will be done and documented on the research section of the wiki by this week.

**Comment by arastasci** [comment]
I have written the mobile app development part on the [page](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis), can you check @Elifnurdeniz?

**Comment by Elifnurdeniz** [comment]
Yes, it looks fine.
