### ISSUE TITLE
Mobile: Create A Navigation Bar

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#315]
## Issue Description
We need a navigation bar that resembles the [mobile mockups](https://github.com/bounswe/bounswe2024group6/wiki/Mobile-Mockups) before the 1st customer presentation. 

## Tasks

- [x] Create a navigation bar

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 17/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar
**Review Deadline:** 20/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
This issue has been completed in #317, can you please close this issue if everything is fine @anilanlar?

**Comment by anilanlar** [comment]
Navigation bar will be reimplemented in a Tab Bar fashion. This version functions well tho.
