### ISSUE TITLE
Mobile: Create Home Page

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#316]
## Issue Description
We need a home page in accordance with the [mobile mockups](https://github.com/bounswe/bounswe2024group6/wiki/Mobile-Mockups). This page is likely to be shown in the 1st customer presentation. It also needs to be linked to the rest of the application via the navigation bar.

## Tasks

- [x] Create a home page
- [x] Link it using the navigation bar

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 18/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 20/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
This issue has been completed in #318, can you please close this issue if everything is fine @anilanlar?

**Comment by anilanlar** [comment]
Home page works alright. I'm closing the issue. Note that it'll be redesigned according to the new mobile design.
