### ISSUE TITLE
Web Application Development Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#32]
A research on Web Application Development will be done and documented on the research section of the wiki by this week.

**Comment by kaanyolcu22** [comment]
@Elifnurdeniz  I have completed the web application development part. Can you check? I could also modify some parts if needed.

**Comment by Elifnurdeniz** [comment]
[link](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis) looks fine.
