### ISSUE TITLE
Redesign Navbar With NextUI

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#320]
## Issue Description
Change the design of the navigation bar to be in more harmony with post cards.

## Tasks

- [x] Redesign navbar

## Estimated Time

**Estimated Time:** 40 minutes

## Deadline

**Deadline:** 19/10/2024 - 16:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 19/10/2024 - 15:00

**Comment by yunusemreozdemir** [comment]
This is implement in #324 can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Looks great, thanks.
