### ISSUE TITLE
Backend: Dockerization

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#325]
## Issue Description

We need to configure the Dockerfile to work with Docker.

## Estimated Time

**Estimated Time:** 2 hours

## Reviewer Assignment

**Reviewer:** @oktayozel

**Comment by kaanyolcu22** [comment]
@oktayozel we have made the dockerization can you check the [pull request](https://github.com/bounswe/bounswe2024group6/pull/328)

**Comment by oktayozel** [comment]
thank you kaan
