### ISSUE TITLE
Mobile: Create a Login Page

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#327]
## Issue Description
We need to create a login page in accordance with the [mobile mockups](https://github.com/bounswe/bounswe2024group6/wiki/Mobile-Mockups). The page needs to be accessible from the login button found in the home page.

## Tasks

- [x] Create a login page
- [x] Link it to the Login button found in the home page

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 19/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 20/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
This issue has been completed in #330, can you please close this issue if everything is fine @anilanlar?

**Comment by anilanlar** [comment]
LGTM!
