### ISSUE TITLE
Application Programming Interface (API) Use and Development Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#33]
A research on Application Programming Interface (API) use and development will be done and documented on the research section of the wiki by this week.

**Comment by eymenesad** [comment]
I added the initial version of the research @skywllker can you work on missing parts

**Comment by Elifnurdeniz** [comment]
Can you do the documentation on [this](https://github.com/bounswe/bounswe2024group6/wiki/Domain-Analysis) page?

**Comment by eymenesad** [comment]
Done. can you check @Elifnurdeniz
