### ISSUE TITLE
[Backend](fix): Mock Data Changes for Post Endpoint

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#336]
## Issue Description

Quoting from @Elifnurdeniz:
"I guess bookmark count is unnecessary. Also, it is better if we make the category (tags) field a list since a content can have multiple tags. Can you name it tags, also?"
We should make the necessary changes - rename category field as tags, make it a list, and remove the bookmark_count field.

## Estimated Time

**Estimated Time:** 15 mins

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz

**Comment by kaanyolcu22** [comment]
I have done it [here](https://github.com/bounswe/bounswe2024group6/pull/379). can you check @Elifnurdeniz

**Comment by oktayozel** [comment]
thanks for your contributions
