### ISSUE TITLE
[Issue Title]: Create data for profile page

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#341]
## Issue Description

I need to create data for the profile page
I need an avatar, username, level, number of followers, number of followers, a list of solved quizzes, a list of own quizzes, a list of own posts
## Tasks

- [] create data for the profile page

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 20/10/2024 - 08:00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22

**Comment by kaanyolcu22** [comment]
thanks , Halil
