### ISSUE TITLE
[Backend]: Implement Quiz View Endpoint

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#344]
## Issue Description

Implement quiz view endpoint that will (for now) return all the quizzes in the database.

## Estimated Time

**Estimated Time:** 1 hour

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 (backend) / @aoengin (mobile)

**Comment by arastasci** [comment]
@kaanyolcu22

**Comment by kaanyolcu22** [comment]
Thanks Aras .
