### ISSUE TITLE
Creating Meeting Notes Template

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#35]
A template for meeting notes will be created and put under the templates section on wiki.

**Comment by yunusemreozdemir** [comment]
I have created the meeting notes template, put it under the templates section and updated the sidebar.
Here is the [Meeting Notes Template](https://github.com/bounswe/bounswe2024group6/wiki//Meeting-Notes-Template).
I also updated the [Meeting 3](https://github.com/bounswe/bounswe2024group6/wiki/Meeting-3) notes, so you can see the new template in use.
Can you check them @Elifnurdeniz ?
