### ISSUE TITLE
Mobile: Navbar Buttons Don't Have a Press Indicator

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#351]
## Issue Description
For better UX, we want a visual cue to let users know when a button is pressed down. This is currently missing from the navigation bar. We could fade out the button or change color or something else, but it must signal to the user that they are pressing a button.

## Tasks

- [x] Make NavBar component buttons have a visual cue when they are pressed.
## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 21/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
This is done in #352, can you please check @aoengin.

**Comment by aoengin** [comment]
I've reviewed and merged the PR.
