### ISSUE TITLE
Start Frontend Profile Page Design

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#355]
## Issue Description

Start implementing the profile page. Not all functionalities are required until the milestone. But a general understanding should be available to customers.

## Tasks

- [x] Create a profile component
- [x] Start designing the page

## Estimated Time

**Estimated Time:** 7 hours

## Deadline

**Deadline:** 21/10/2024 - 12:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir @alitariksahin 
**Review Deadline:** 21/10/2024 - 14:00

**Comment by Elifnurdeniz** [comment]
I'm done with the design for the first milestone. Can you check and close the issue @yunusemreozdemir @alitariksahin?

**Comment by alitariksahin** [comment]
I am amazed
