### ISSUE TITLE
Mobile: Make the Navbar Button Extensible

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#358]
## Issue Description
We need the Navbar component's buttons to be extensible. This is necessary because we may want to implement custom functionality for the Navbar depending on the page.

## Tasks

- [x] Make the Navbar component accept 4 optional props: homeOnPress, quizOnPress, forumOnPress, profileOnPress
- [x] Change the onPress functions of each button in the Navbar by adding the optional props if they exist.

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 21/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
I have finished this task in #359, can you please check @aoengin

**Comment by aoengin** [comment]
Thanks Yagiz!
