### ISSUE TITLE
Documentation of Git Research

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#36]
Will collect what we learnt about Git and document it on the research section on wiki.

**Comment by ebruozcaki** [comment]
Hi Elif. I have documented the research. We can close the issue if you approve.

**Comment by Elifnurdeniz** [comment]
[link](https://github.com/bounswe/bounswe2024group6/wiki/Git-as-a-Version-Management-System) looks fine. I'm closing the issue.
