### ISSUE TITLE
[BACKEND]:Postman Group Set Up and Translate the self written endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#363]
## Tasks

- [] Create the group
- [] add and test endpoints

## Estimated Time

**Estimated Time:** 1hours

## Deadline

**Deadline:** 20/10/2024 

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 20/10/2024

**Comment by oktayozel** [comment]
<img width="1722" alt="Screenshot 2024-10-21 at 20 36 01" src="https://github.com/user-attachments/assets/49394aa9-8d79-4c98-a1ec-77a5a9ab1718">
@kaanyolcu22

**Comment by kaanyolcu22** [comment]
Thanks , Oktay.
