### ISSUE TITLE
[Backend]: Profile Model, Serializer, View and Update Functionality

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#364]
## Issue Description
Code the user profile including models, serializers, basic view and update functionalities.

## Tasks

- [x] Model
- [x] serializer
- [x] urls
- [x] viewprofile()
- [x] updateprofile()
- [x] postman endpoints
- [ ] 

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 22/10/2024

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 23/10/2024

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/pull/369 

@arastasci  can you pull and close the issue also after reviewing

**Comment by arastasci** [comment]
LGTM!!!
