### ISSUE TITLE
Contemplate and create a personal wiki page: Oktay Özel 

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#37]
I will create my personal wiki page according to the structure defined in the meeting.

**Comment by oktayozel** [comment]
Hello, I have created my tentative page. It can be seen [here](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Effort-:-Oktay-%C3%96zel). One who sees this can you please check and close the issue:)

**Comment by kaanyolcu22** [comment]
Thanks @oktayozel I am closing
