### ISSUE TITLE
Meeting Notes: Weekly Meeting 4

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#374]
## Issue Description
A new wiki article must be created under the Meeting Notes section in accordance with our Meeting Notes template for the Weekly Meeting 4 (Sunday, 20th of October 2024, 12:20).

## Tasks
- [x] Create a Meeting Notes wiki article for this meeting

## Estimated Time
**Estimated Time:** 30 mins

## Deadline
**Deadline:** 21/10/2024 - 21:00

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 21/10/2024 - 23:59

**Comment by aoengin** [comment]
I've created the [weekly meeting notes page](https://github.com/bounswe/bounswe2024group6/wiki/CMPE-451-Weekly-Meeting-4). @YavizGuldalf

**Comment by YavizGuldalf** [comment]
The meeting notes look good, and it's also been added to the sidebar so good job.
