### ISSUE TITLE
[Mobile]: Quiz Creation Flow - QuizCreationQuestionList Page

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#376]
## Issue Description

UI components are implemented in QuizCreationQuestionList page, however, the following changes should be done as the first milestone tasks. Some of the changes include editing the alignment of the UI components and their functionalities. Navigation operations are going to be handled in another issue. 

## Tasks
1- QuizCreationQuestionList:

- [x] The page needs to have a little margin on the top for the Navbar to be visible.
- [x] The garbage can icon should delete that question from the list.

## Deadline

**Deadline:**  22/10/2024- 08:00

## Reviewer Assignment

**Reviewer:** @anilanlar  
**Review Deadline:**  22/10/2024- 08:00

**Comment by YavizGuldalf** [comment]
This issue was completed by @aoengin in PRs #365 and #356, can you please check if everything is okay, @anilanlar?

**Comment by anilanlar** [comment]
LGTM!
