### ISSUE TITLE
[Backend]: Fix Mock Data Creation

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#380]
## Issue Description

Quiz mock data creation at app start was deleted in a commit, we need to fix that and also change the type of response that quiz feed endpoint returns.

## Reviewer Assignment

**Reviewer:** @oktayozel

**Comment by arastasci** [comment]
@oktayozel with #381 this issue must be completed, can you check?

**Comment by oktayozel** [comment]
thanks aras
