### ISSUE TITLE
Frontend: add filter components to the forum page

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#382]
## Issue Description

 A filtering view is needed for first customer presentation.
## Tasks

- [] ~Task 1~ (Pending)

## Estimated Time

**Estimated Time:** 45 minutes

## Deadline

**Deadline:** 21/10/2024 - 20:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 21/10/2024 - 20:10

**Comment by alitariksahin** [comment]
@Elifnurdeniz Can you check if it is done completely

**Comment by Elifnurdeniz** [comment]
Thanks
