### ISSUE TITLE
Adjust Navbar Spacings

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#385]
## Issue Description
Navbar has unnecessary empty spaces around it. Adjust it to fit more in the page.

## Tasks

- [x] Adjust navbar

## Estimated Time

**Estimated Time:** 20 minutes

## Deadline

**Deadline:** 21/10/2024 - 21:30

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 21/10/2024 - 22:00

**Comment by alitariksahin** [comment]
Thumbs up!
