### ISSUE TITLE
Mobile: New Version of Quiz Creations

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#386]
## Issue Description
The current version is outdated, the quiz creation page needs a description instead of audience.

## Tasks

- [x] Update the quiz creation page

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 22/10/2024 - 08:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:**  22/10/2024 - 08:00

**Comment by aoengin** [comment]
I've completed the requested changes and made some additional changes. Please see the related [PR](https://github.com/bounswe/bounswe2024group6/pull/407). @YavizGuldalf
