### ISSUE TITLE
FRONTEND: Make profile button clickable

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#387]
## Issue Description

The profile icon should be clickable. Implement a button feature there.
## Tasks

- [x] Make profile icon clickable

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 21/10/2024- 23:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 21/10/2024- 23:10

**Comment by Elifnurdeniz** [comment]
I adjusted the design of it can you check [here](https://github.com/bounswe/bounswe2024group6/pull/392)?

**Comment by alitariksahin** [comment]
Keep it up!
