### ISSUE TITLE
Create a personal wiki page for myself, Battal HAZAR

### ISSUE THREAD

**Issue by battal255** [bounswe/bounswe2024group6#39]
I am going to create a personal wiki page for myself according to the template determined in the [meeting](https://github.com/bounswe/bounswe2024group6/wiki/Meeting-2-%E2%80%90-25.02.2024-Sunday).

**Comment by battal255** [comment]
i think I complete the task, can you check [the page](https://github.com/bounswe/bounswe2024group6/wiki/Personal-Wiki-&-Effort--Battal-Hazar) @kaanyolcu22?

**Comment by kaanyolcu22** [comment]
@battal255 Thanks , I've checked. I 'm closing the issue
