### ISSUE TITLE
FRONTEND: fix filtering view

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#394]
## Issue Description

There is a problem with the view
## Estimated Time

**Estimated Time:** 15 minutes

## Deadline

**Deadline:** 21/10/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:**  21/10/2024 - 23:00

**Comment by alitariksahin** [comment]
@Elifnurdeniz can you check

**Comment by Elifnurdeniz** [comment]
Looks good, thanks.
