### ISSUE TITLE
Frontend: Connect Profile Page With Backend

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#399]
## Issue Description

Instead of using mock data,  take the data from backend. Also, give relative path to the profiles based on username.

## Tasks

- [x] Connect profile page with backend
- [x] Handle dynamic routing

## Estimated Time

**Estimated Time:** 40 minutes

## Deadline

**Deadline:** 21/10/2024 - 23:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 21/10/2024 - 23:30

**Comment by yunusemreozdemir** [comment]
This is done in #409 can you check @Elifnurdeniz ?
