### ISSUE TITLE
Frontend: Connect Forum Page With Backend

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#400]
## Issue Description

Instead of using mock data,  take the data from backend.

## Tasks

- [x] Connect forum page with backend

## Estimated Time

**Estimated Time:** 20 minutes

## Deadline

**Deadline:** 21/10/2024 - 23:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz
**Review Deadline:** 21/10/2024 - 23:30

**Comment by yunusemreozdemir** [comment]
This is done in #408 can you check @Elifnurdeniz ?
