### ISSUE TITLE
Mobile: Connect Log-in and Sign-up Pages to the Backend

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#401]
## Issue Description
The log in and sign up pages have to be connected to the backend and the necessary changes have to be made to the UI, including potentially Toasts, button connections, error messages etc.

## Tasks

- [x] Connect and fix Register Page.
- [x] Connect and fix Log In Page.

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 22/10/2024 - 08:00

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 22/10/2024 - 08:00

**Comment by aoengin** [comment]
Well done! #409
