### ISSUE TITLE
Creating a RACI-RAM Matrix	

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#41]
Create weekly RAM matrix for this week in coordination with the meeting notes.

**Comment by Elifnurdeniz** [comment]
@yunusemreozdemir hey, im done with the RAM. Can you it it [here](https://github.com/bounswe/bounswe2024group6/wiki/Responsibility-Assignment-Matrix) ?

**Comment by yunusemreozdemir** [comment]
Excellent! I reviewed it, closing this issue.
