### ISSUE TITLE
FRONTEND: Fix Profile Page View

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#411]
## Issue Description

I want to see solved quizzes first when I go to profile page
## Tasks

- [] ~Switch quizzes and posts pages

## Estimated Time

**Estimated Time:** 15 minutes

## Deadline

**Deadline:** 22/10/2024 - 00:30

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 22/10/2024 - 00:30

**Comment by Elifnurdeniz** [comment]
[You can see the commit [here](url)](https://github.com/bounswe/bounswe2024group6/pull/414)

**Comment by alitariksahin** [comment]
Great Work
