### ISSUE TITLE
Create Readme File

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#416]
## Issue Description

Create a Readme.md file and explain how to run the web project on your local.

## Tasks

- [x] Create Readme file

## Estimated Time

**Estimated Time:** 20 minutes

## Deadline

**Deadline:** 22/10/2024 - 01:30

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 22/10/2024- 01:40

**Comment by Elifnurdeniz** [comment]
We are done can you check @alitariksahin ?

**Comment by alitariksahin** [comment]
real
