### ISSUE TITLE
Mobile: Prepare Mobile for Deployment

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#419]
## Issue Description
We need to prepare the mobile project for deployment. For this, we need to create a documentation detailing how to build the project. Also, we need to change the app name and version.

## Tasks

- [x] Change app metadata (name, version etc.)
- [x] Write a documentation detailing the build steps.

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 22/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 22/10/2024 - 23:59

**Comment by aoengin** [comment]
#423 fixes this issue.
