### ISSUE TITLE
Creating Banner and Updating Wiki Page

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#42]
Create a banner for the homepage and make it look more beautiful. Update the missing parts such as meetings etc...

**Comment by oktayozel** [comment]
@ebruozcaki how is it going?

**Comment by oktayozel** [comment]
@anilanlar  hello anıl I have designed and uploaded our banner and updated the information both for readme part and our Wiki! Can you check and close the issue

**Comment by anilanlar** [comment]
Thank you for the design and your efforts on Wiki. I am closing the issue.
