### ISSUE TITLE
Creating Scenarios for Requirements Assignment

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#43]
Create 5 scenearios for the project and document them.

**Comment by eymenesad** [comment]
done can you check @oktayozel

**Comment by oktayozel** [comment]
Here I am dropping a [link](https://github.com/bounswe/bounswe2024group6/wiki/Scenarios) to the page for availibility.

**Comment by oktayozel** [comment]
thank you @eymenesad !

**Comment by oktayozel** [comment]
Hey! I have checked some Scenario examples and ours is quite open for advancements. @arastasci can you work on it a bit please?

**Comment by eymenesad** [comment]
Hey! We opened a new issue for updating the scenarios according to new mockup batch. I will close this issue
