### ISSUE TITLE
Prerelease: Version 0.1.0

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#431]
## Issue Description
We need to have this prerelease ready before the 1st customer milestone as it is one of the required deliverables. It needs to contain an apk and our source code as well as build instructions.

## Tasks

- [x] Publish the prerelease 0.1.0

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 22/10/2024 - 08:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 22/10/2024 - 08:00

**Comment by aoengin** [comment]
Please see the [pre-release](https://github.com/bounswe/bounswe2024group6/releases/tag/customer-milestone-1). @Elifnurdeniz

**Comment by Elifnurdeniz** [comment]
Looks correct, thanks.
