### ISSUE TITLE
Adjust Project Deliverables

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#432]
## Issue Description

[This issue](https://github.com/bounswe/bounswe2024group6/issues/297) addresses some inconsistencies between mock-ups, diagrams and requirements. Do the changes mentioned there.

## Tasks

- [x] Finish the changes

## Estimated Time

**Estimated Time:** 20 minutes

## Deadline

**Deadline:** 25/10/2024 - 13:30

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 25/10/2024 - 17.:00

**Comment by Elifnurdeniz** [comment]
All the changes are made which are listed in the issue. Can you check @YavizGuldalf?

**Comment by YavizGuldalf** [comment]
I have checked the requirement for all the issues mentioned, they seem to have been addressed. Good job.
