### ISSUE TITLE
Research: Activity Streams 2.0

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#447]
## Issue Description
We had previously decided to use Activity Streams 2.0 as our W3C standard for this project. However, we have thus far not made much progress when it comes to understanding or implementing it. We need to know which teams get affected and how exactly we make our project Activity Streams 2.0 compliant. We need to create a more detailed document about how it affects our project and how to implement it. Also, in order to demonstrate how it is used, it's best to include at least one example in our own codebase, if it's plausible.

## Tasks

- [x] Create a new research article in the wiki about Activity Streams 2.0: It's benefits, rules and how it can be applied to our project should be clearly stated.
- [x] (Optional) Modify a piece of code in the front-end application to make use of Activity Streams 2.0. This might require involvement from the backend team.

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 17/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 20/11/2024 - 23:59

**Comment by alitariksahin** [comment]
[Activity Streams 2.0](https://github.com/bounswe/bounswe2024group6/wiki/Activity-Streams-2.0-Detailed-Research)
