### ISSUE TITLE
Choosing Tags for Quizzes and Forum

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#448]
## Issue Description
For now, we are planning on using a predetermined set of Tags. We need to decide what these tags will be, and to which kind of entities(quizzes, forum posts, forum comments) they can be attached to. The tags should be relevant to our app's goals. Example tags are [CEFR](https://www.coe.int/en/web/common-european-framework-reference-languages/level-descriptions) level tags or different concepts and terms related to language learning in particular, like vocabulary, grammar, etymology etc. The tags should ideally not be too specific. Some tags may be quiz or forum specific. A table to show this information would be ideal.

## Tasks

- [x] Create a wiki article detailing the tags we will be using in the app 

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 10/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 13/11/2024 - 23:59

**Comment by Elifnurdeniz** [comment]
I added the inital tags [here](https://github.com/bounswe/bounswe2024group6/wiki/Application-Tags-(Draft)) as a draft. I will add more tags after discussing with backend team.
