### ISSUE TITLE
Document System Requirements

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#45]
Work on system requirements of the project and document them in a way presented in lecture slides.

**Comment by anilanlar** [comment]
Completed the system requirements of the project with @battal255. It could be found [here](https://github.com/bounswe/bounswe2024group6/wiki/Requirements).

**Comment by oktayozel** [comment]
Can you type it in [dropdown](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61) format. @anilanlar @battal255

**Comment by battal255** [comment]
We turned dropdown style. It could be found [here](https://github.com/bounswe/bounswe2024group6/wiki/Requirements)

**Comment by oktayozel** [comment]
thanks so much:)
