### ISSUE TITLE
[Mobile]: Fix the Mobile HTTP Request Issue

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#462]
## Issue Description
We're facing issues with HTTP Requests sent from our mobile application. It needs to be resolved.

## Tasks

- [x] Do research and inform team members.
- [x] Come up with a solution and Implement it.
## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 8/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 10/11/2024 - 23:59

**Comment by aoengin** [comment]
This task is completed. Please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/483). @anilanlar
