### ISSUE TITLE
[Mobile]: Create Post Card and Comment Card Components

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#469]
## Issue Description
Create Post Card and Comment Card components. They are going to be used in several pages. The pictures below is only for functionality purposes, it does not represent our updated UI.

### Post Card component
<img width="304" alt="image" src="https://github.com/user-attachments/assets/48a05531-7ec6-4507-b344-acfbdd4d1aa8">

### Comment Card component
<img width="288" alt="image" src="https://github.com/user-attachments/assets/c928d1c6-5df3-4fae-9939-de63db67101c">

## Tasks

- [ ] Create the Post Card component.
- [ ] Create the Comment Card component.

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 8/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf   
**Review Deadline:** 10/11/2024 - 23:59

**Comment by YavizGuldalf** [comment]
I guess that this issue is completed as we already have these components in the main branch. Therefore, I am closing this issue as completed. Feel free to reopen it if I am wrong.
