### ISSUE TITLE
Backend : Authentication Endpoints Move to another view file

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#470]
## Issue Description
In order to gat a more organized views I am going to organize views in a better way.

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 3 Nov

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 3 Nov

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/compare/main...BACKEND-DEV

sorry I did it on the dev branch accidentally but it is here.

@arastasci can you check and close it.

I moved login, logout, and signup to another views file

**Comment by arastasci** [comment]
lgtm
