### ISSUE TITLE
Create Glossary Template

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#48]
Create a template for Glossary and define some keywords as example. Remind this topic in the next weeks meeting for further improvements.

**Comment by Elifnurdeniz** [comment]
@oktayozel hey, I've started it [here](https://github.com/bounswe/bounswe2024group6/wiki/Requirements). Can you check and close the issue if all members are satisfied with it?

**Comment by oktayozel** [comment]
thank you @Elifnurdeniz !
