### ISSUE TITLE
[FRONTEND]: Create Quiz Feed 

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#485]
## Issue Description

 We need a quiz card component which will be displayed in both quiz feed and in follow-up quiz recommendation.
## Tasks

- [x] Create Quiz Card 

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 14/11/2024 - 20:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 15/11/2024 - 20:00

**Comment by Elifnurdeniz** [comment]
I added the quiz card and displayed it in forum in this [pr](https://github.com/bounswe/bounswe2024group6/pull/498). I will later add the recommended quiz feature.
