### ISSUE TITLE
[Lab]: Prepare 2 User Stories

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#489]
## Issue Description

We need to write 2 user stories that both describe usual user scenarios and highlight our features.

## Estimated Time

**Estimated Time:** 90 mins

## Reviewer Assignment

**Reviewer:** @arastasci

**Comment by Elifnurdeniz** [comment]
We wrote the scenarios and added them to the wiki in [here](https://github.com/bounswe/bounswe2024group6/wiki/Lab%E2%80%906-User-Stories). Halil added the night mode scenario and I added the quiz resume scenario. Can you check @arastasci ?
