### ISSUE TITLE
[Lab] Frontend: Implement Night Mode Feature

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#490]
## Issue Description

The feature shall provide users a button which changes UI components appearance to light texts on dark colors, opposed to the only option we have, dark-on-light colors.

## Estimated Time

**Estimated Time:** 90 mins

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz

**Comment by Elifnurdeniz** [comment]
It is done and added to the main branch.
