### ISSUE TITLE
[Lab] Mobile: Improve Similarities with Web UI

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#491]
## Issue Description

In order to provide a consistent user experience, we need to make the UI of mobile and web as similar as possible - so we shall look into ways of improving it, taking our web UI as reference for now.

## Estimated Time

**Estimated Time:** 90 mins

## Reviewer Assignment

**Reviewer:** @anilanlar

**Comment by aoengin** [comment]
@anilanlar Please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/493).
