### ISSUE TITLE
[Lab] Mobile: Implement Night Mode Feature

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#492]
## Issue Description

The feature shall provide users a button which changes UI components' appearance to light texts on dark colors, opposed to the only option we have, dark-on-light colors.

## Estimated Time

**Estimated Time:** 90 mins

## Reviewer Assignment

**Reviewer:** @YavizGuldalf

**Comment by aoengin** [comment]
Please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/493).
