### ISSUE TITLE
[Lab] Frontend: Implement Quiz Resume Feature

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#495]
## Issue Description

We need to provide users a way to continue unfinished quizzes from the question they left off.

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir

**Comment by Elifnurdeniz** [comment]
I added the quit quiz button in this [pr](https://github.com/bounswe/bounswe2024group6/pull/493). It doesn't have a functionality now but it will be added in the future.
