### ISSUE TITLE
Make a Related Software Analysis

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#50]
Perform an analysis of the selected domain by examining related software systems. Document your observations of their features specifically noting what is missing.

**Comment by arastasci** [comment]
I've done the analysis, can you check the [page](https://github.com/bounswe/bounswe2024group6/wiki/Related-Software-Analysis) @oktayozel ?

**Comment by oktayozel** [comment]
thank you aras!
