### ISSUE TITLE
Backend: Deploying Backend Separately 

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#515]
## Issue Description

We need to deploy the backend separately in an EC2 instance from its development branch for mobile and web frontends to use with ease.
## Tasks

- [x] ~Deploy in EC2 instance~ (Completed)

## Estimated Time

**Estimated Time:** 2 hours

## Reviewer Assignment

**Reviewer:** @YavizGuldalf

**Comment by YavizGuldalf** [comment]
This issue has been completed for a long time, sorry for the delay in closing it guys.
