### ISSUE TITLE
Create a Mock-Up

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#52]
Contemplate the pages of the SIM browser and create a mock-up. Draw pages if necessary.

**Comment by yunusemreozdemir** [comment]
Mock-ups are complete! They can be seen in the [Scenarios and Mockup](https://github.com/bounswe/bounswe2024group6/wiki/Scenarios-And-Mockup) page. Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Looks great! Thanks.
