### ISSUE TITLE
Frontend: Resolve Merge Conflicts in PRs #478, #493, #500, #522

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#523]
## Issue Description
These PRs have some conflicts that needs to be resolved before they are merged.

## Tasks
- [x] #478 
- [x] #493 
- [x] #500 
- [x] #522 

## Estimated Time
**Estimated Time:** 1 hour

## Deadline
**Deadline:** 20/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 21/11/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in PRs #478, #493, #500, #522 can you check @Elifnurdeniz?

**Comment by Elifnurdeniz** [comment]
Everything looks fine(amazing)
