### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by eymenesad** [bounswe/bounswe2024group6#54]
(a) Summary of project and overall status
(b) List the status of deliverables
(c) Decisions and choices you have made and your assessment regarding them. These include,
but are not limited to, conventions and choices related to issue management, meetings, and
wiki documentation)
(d) Challenges you have met as a group (if any), and how you have or plan to overcome them

**Comment by oktayozel** [comment]
@eymenesad we have written it in a collaborative manner. Can you check it please via this [link](https://hackmd.io/ZWiC5FNpTXi_dKAR4pojJQ)? @arastasci @anilanlar

**Comment by eymenesad** [comment]
Well done, appreciated.
