### ISSUE TITLE
Fix Profile button

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#540]
## Issue Description

There is a rectangular border popping up when clicked on profile button on left top corner, which we shouldn't see.
## Tasks

- [x] Remove the border

## Estimated Time

**Estimated Time:** 45 minutes

## Deadline

**Deadline:** 22/11/2024 - 23:45

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 23/11/2024 - 07:45

**Comment by Elifnurdeniz** [comment]
It's done in [here](https://github.com/bounswe/bounswe2024group6/pull/541). Can you check @alitariksahin ?
