### ISSUE TITLE
Create Profile Edit Page

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#542]
## Issue Description

Users should be able to edit their profile page
## Tasks

- [x] Creating editing page

## Estimated Time

**Estimated Time:** 6 hours

## Deadline

**Deadline:** 24/11/2024 - 10:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024 - 23:00

**Comment by Elifnurdeniz** [comment]
It is done in [here](https://github.com/bounswe/bounswe2024group6/pull/598) @alitariksahin .
