### ISSUE TITLE
Make Filtering Functional

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#551]
## Issue Description

  Filtering and listing need to be made functional
## Tasks

- [x] fix filtering

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 23/11/2024 - 23:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024 - 23:00

**Comment by Elifnurdeniz** [comment]
Done in [here](https://github.com/bounswe/bounswe2024group6/pull/567/) @alitariksahin .
