### ISSUE TITLE
Implement visiting the profile pages of other users

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#559]
## Issue Description

Users should be able to see other users' profile pages, this redirection should be done by clicking on their profile avatar either in notifications or in comments or posts section.
## Tasks

- [x] Create guest user view.
- [x] Implement visiting functionality

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 24/11/2024 - 20.00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024 - 23.00

**Comment by Elifnurdeniz** [comment]
It is done in these commits [1](https://github.com/bounswe/bounswe2024group6/pull/580/commits/55df37a348eff189ec73bbb7c01addd7dd312e5f), [2](https://github.com/bounswe/bounswe2024group6/pull/580/commits/c43ddd7c32c6dd3711241e2b7741f0d262a4e2f9). Can you check @alitariksahin ?

**Comment by Elifnurdeniz** [comment]
Follow button logic will be implemented when backend is ready.
