### ISSUE TITLE
Implement Comments Section of the Posts

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#560]
## Issue Description

Users should be able to make comments both to the posts and the other comments.
## Tasks

- [x] Create comment composing view
- [x] List comments
- [x] Enable recursive comments functionality

## Estimated Time

**Estimated Time:**  4 hours

## Deadline

**Deadline:** 24/11/2024- 20:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024- 23:00

**Comment by yunusemreozdemir** [comment]
This is done in #612, can you check @Elifnurdeniz?
