### ISSUE TITLE
Evaluation of tools and processes

### ISSUE THREAD

**Issue by eymenesad** [bounswe/bounswe2024group6#57]
Evaluation of tools and processes you have used to manage your team project. This is a lessons
learned from the project development decisions made so far – how effectively are the tools are being
utilized & what changes (if any) are needed as you move forward?

**Comment by arastasci** [comment]
I also contributed to the evaluation of tools and processes part. @battal255 may review and edit it as he sees fit. As we are editing the milestone report at HackMD right now, I can't provide you with a link though. @eymenesad

**Comment by yunusemreozdemir** [comment]
I checked it, great work, it can be found in [Milestone 1 Report](https://github.com/bounswe/bounswe2024group6/wiki/Milestone-1-Report).
