### ISSUE TITLE
Configure Post Related Endpoints Specific  To User

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#578]
## Issue Description
 Modify the endpoints so that the likes , follow and bookmark endpoints for frontend so that they will specific to the user 

## Estimated Time

**Estimated Time:**  2 hours

## Deadline

**Deadline:** 23/11/2024 : 00:00

## Reviewer Assignment

**Reviewer:** @arastasci

**Comment by kaanyolcu22** [comment]
I am done can you close this issue @arastasci

**Comment by arastasci** [comment]
Good work.
