### ISSUE TITLE
Organising Wiki Sidebar

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#6]
The pages in the sidebar can be organised in a way that there will be main and sub pages. In that way, wiki will not get messy in the future.

**Comment by arastasci** [comment]
i made a custom sidebar using [a 3rd party tool](https://github.com/adriantanasa/github-wiki-sidebar). Note that we need to continuously change the sidebar as the wiki frequently changes.

**Comment by arastasci** [comment]
sorry, i forgot to close the issue.
