### ISSUE TITLE
Fill the Work Done Table for Milestone-1 Report 

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#60]
Fill the table according to your contributions to the project as specified in the template [here](https://github.com/bounswe/bounswe2024group6/wiki/Work-Done-By-Each-Member).

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/wiki/Work-Done-By-Each-Member/ can someone check and close? thanks:)

**Comment by battal255** [comment]
ı checked.It looks ok. I closed.
