### ISSUE TITLE
Backend: Auxiliary Quiz Endpoints

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#610]
## Issue Description

We need to improve the quiz endpoints as follows:
- Add created quiz endpoints in which the user receives all quizzes they've created.
- Add solved quiz endpoints in which the user receives the *quiz* instances they've solved.
- Add liked quiz endpoints in which the user receives the quizzes they've liked.
- add booomarked quiz endpoints in which the user receives the quizzes they've bookmarked.

## Estimated Time

**Estimated Time:** 1hour

## Reviewer Assignment

**Reviewer:** @YavizGuldalf

**Comment by YavizGuldalf** [comment]
Good work, @arastasci
