### ISSUE TITLE
Fill the Work Done Table for Milestone-1 Report - Aras Tasci

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#66]
Fill the table according to your contributions to the project as specified in the template [here](https://github.com/bounswe/bounswe2024group6/wiki/Work-Done-By-Each-Member).

**Comment by arastasci** [comment]
done, can you check [it](https://github.com/bounswe/bounswe2024group6/wiki/Work-Done-By-Each-Member) @eymenesad?

**Comment by yunusemreozdemir** [comment]
I checked it, excellent work, properly documented.
