### ISSUE TITLE
Mobile: Successful Build but App keeps stopping

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#670]
## Issue Description
The local build process completes successfully but the resulting app does not work properly, it keeps stopping. We need to find a fix ASAP so that we can deliver a working APK file before the second customer milestone. The code I use for the build is:

`eas build -p android --local --profile preview`

And then I later test this in the android virtual machine using `adb install XXXXX.apk`. I have also tested it in my personal mobile phone, and it doesn't work there either.

## Tasks

- [ ] Find a way to fix the 'App keeps stopping' error.

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 25/11/2024 - 21:30

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 29/11/2024 - 21:30

**Comment by aoengin** [comment]
Related [PR](https://github.com/bounswe/bounswe2024group6/pull/681).
