### ISSUE TITLE
Backend: Fix Multiple Quizzes Returning in Solved Quizzes Endpoint

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#678]
## Issue Description

We're returning every quiz progresses' quiz separately, and these overlap, we need to return the unique quizzes.

## Estimated Time

**Estimated Time:** 30 mins

## Reviewer Assignment

**Reviewer:** @YavizGuldalf

**Comment by YavizGuldalf** [comment]
This problem has been fixed, thank you.
