### ISSUE TITLE
Create Mobile Mockups

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#68]
Example mobile mockup pages will be created for the main pages in the web/desktop [mockup](https://github.com/bounswe/bounswe2024group6/wiki/Scenarios-And-Mockup).

**Comment by yunusemreozdemir** [comment]
I created 5 example mobile mockup pages. I chose the ones that would differ in mobile in some way. I think all of the pages in our original mockup can be derived from these designs. They can be found in the [Milestone 1 Report](https://github.com/bounswe/bounswe2024group6/wiki/Milestone-1-Report). Can you check @Elifnurdeniz ?

**Comment by Elifnurdeniz** [comment]
Yes, looks fine.
