### ISSUE TITLE
BACKEND: Test Lexvo Endpoints

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#688]
## Issue Description
 Testing Lexvo endpoints if they are functioning well.

## Deadline

**Deadline:** 26/11/24- 19:00

## Reviewer Assignment

**Reviewer:** @arastasci

**Comment by kaanyolcu22** [comment]
I am done can you check @arastasci

**Comment by arastasci** [comment]
Sure thing
