### ISSUE TITLE
Draw Class Diagrams

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#69]
Drawing class diagrams of our application. 4 members of our team who assigned will be doing this task and all members will check after it. Members who assigned to this issue could open sub-issues after determining working parts.

**Comment by Elifnurdeniz** [comment]
We gathered as a group and divided tasks. I will open sub-task issues and this issue will be closed after they are all finished.

**Comment by Elifnurdeniz** [comment]
All members are done with the design. The final work is [here](https://github.com/bounswe/bounswe2024group6/wiki/Class-Diagrams).
