### ISSUE TITLE
Creating Implemented Requirements

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#704]
## Issue Description

Implemented requirements should be listed for milestone 2.

## Tasks

- [x] List implemented requirements

## Estimated Time

**Estimated Time:** 40 minutes

## Deadline

**Deadline:** 25/11/2024 - 21:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 25/11/2024 - 21:30

**Comment by Elifnurdeniz** [comment]
It is listed in [here](https://github.com/bounswe/bounswe2024group6/wiki/Implemented-Requirements-Milestone%E2%80%902). Can you check @YavizGuldalf ?

**Comment by YavizGuldalf** [comment]
Thanks @Elifnurdeniz, good job.
