### ISSUE TITLE
Project Plan for Milestone 3

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#709]
## Issue Description
 A comprehensive project plan is required for milestone 3.

## Estimated Time

**Estimated Time:** 1 hours 

## Deadline

**Deadline:** 29/11/2924-17:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf

**Comment by kaanyolcu22** [comment]
I am done with the project plan for milestone 3 , can you check @YavizGuldalf [link](https://sharing.clickup.com/9018699392/g/h/8crwvm0-398/3909d6139f5e8c6)

**Comment by YavizGuldalf** [comment]
I am not sure that the link you provided is correct, how am I supposed to see the project plan here? Also, can you please upload the screenshots of the finished project plan to our wiki [here](https://github.com/bounswe/bounswe2024group6/wiki/General-Project-Plan).


<img width="1440" alt="Screenshot 2024-11-29 at 16 01 59" src="https://github.com/user-attachments/assets/e6396889-4cb4-45c1-aab5-373afa3497a7">
