### ISSUE TITLE
Lab Report: 3rd of December, 2024

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#714]
## Issue Description
This week's lab meeting will focus on primary features, domain-specific features, APIs and their documentation, document standards, testing strategies.

## Tasks
- [x] Write a lab report using the [lab report template](https://github.com/bounswe/bounswe2024group6/wiki//Lab-Report-Template)

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 03/12/2024 - 19:45

## Reviewer Assignment
**Reviewer:** @YavizGuldalf  
**Review Deadline:** 03/12/2024 - 19:59

**Comment by YavizGuldalf** [comment]
I see that this issue has been completed, and the related wiki page is [here](https://github.com/bounswe/bounswe2024group6/wiki/Lab-Meeting-8). I have taken the liberty to add it to the sidebar as well. I am now closing this issue, thank you @anilanlar.
