### ISSUE TITLE
Lab 8 Testing and Coverages

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#716]
## Issue Description

Document Testing coverages of the project and open a PR.

## Tasks

- [x] Frontend
- [x] Backend
- [x] Mobile

## Estimated Time

**Estimated Time:** 1.5 hours

## Deadline

**Deadline:** 3 Dec

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 3 Dec

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/wiki/Testing-Strategies

**Comment by alitariksahin** [comment]
well done
