### ISSUE TITLE
Refresh Token Endpoint

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#729]
## Issue Description
Implement a refresh token endpoint for generating a new access token.

## Tasks
- [ ] Write refresh token endpoint

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
LGTM.
