### ISSUE TITLE
Refractor Codebase

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#730]
## Issue Description
Clean and refactor the codebase.

## Tasks
- [ ] Clean the codebase

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
🤔
