### ISSUE TITLE
Get User Feed Endpoint

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#732]
## Issue Description
Implement the user feed endpoint.

## Tasks
- [ ] Write get user feed endpoint

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
LGTM.
