### ISSUE TITLE
Create Post Class Diagrams

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#74]
Creating Post Class Diagrams according to requirements. Class diagram team members will check it when it's done.

**Comment by arastasci** [comment]
i created the "Post" part of the class diagrams. Can anyone check the Miro Board? @Elifnurdeniz @battal255 @skywllker

**Comment by Elifnurdeniz** [comment]
Can you reorganise it so that the content class will be the parent class for comment and posts?

**Comment by arastasci** [comment]
ok, i've done the edit. can you check again? @Elifnurdeniz

**Comment by Elifnurdeniz** [comment]
Looks fine. Thanks.
