### ISSUE TITLE
Backend: Revert Changes in 'get-meaning' Endpoint Logic

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#745]
## Issue Description
After discussing with @kaanyolcu22, we have decided to revert the changes made to the get-meaning endpoint so that it returns all meanings once again. This decision was made to simplify the logic on the backend and delegate filtering or selection responsibilities to the client side (Mobile and Frontend).

## Tasks
- [x] Update the endpoint to return all meanings.

## Estimated Time
**Estimated Time:** 30 mins

## Deadline
**Deadline:** 10/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @kaanyolcu22  
**Review Deadline:** 13/12/2024 - 23:59

**Comment by aoengin** [comment]
@kaanyolcu22 please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/746).

**Comment by kaanyolcu22** [comment]
I reviewed the PR , you can merge thanks
