### ISSUE TITLE
Lab: Final Presentation Plan

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#753]
## Issue Description

You should have a clear plan for the final presentation, including the user journey through the demo, the features you will show, and the outline of the presentation
## Tasks

- [x] Write a documentation regarding the final presentation plan
## Estimated Time

**Estimated Time:** 90 minutes

## Deadline

**Deadline:** 10/12/2024 - 20:00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 10/12/2024 - 23:00

**Comment by YavizGuldalf** [comment]
The page is ready for review. You can find it [here](https://github.com/bounswe/bounswe2024group6/wiki/Demo-Plan-for-Customer-Milestone-3).
