### ISSUE TITLE
Requirements Review and Update 

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#77]
The requirements should be reviewed and modified appropiately to the needs and structure of the project .

**Comment by oktayozel** [comment]
@kaanyolcu22 Can u check updated version of [requirements](https://github.com/bounswe/bounswe2024group6/wiki/Requirements)

Thank you so much.

Updates:
* Requirements for following people and semantic search added.
* Requirements for undoing operations are added.
* Requirements about how users post are added.
*Guest requirements are rewritten in a correct format
* Wording of system requirements are updated.
* Some user keywords are converted to registered user.

**Comment by kaanyolcu22** [comment]
Thanks , it looks nice.
