### ISSUE TITLE
Backend: Admin Ban Endpoint

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#786]
## Issue Description

We should implement an endpoint that allows admins to ban users.

## Estimated Time

**Estimated Time:** 30 mins

## Deadline

**Deadline:** 13/12/2024 10.00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 13/12/2024 23.59

**Comment by YavizGuldalf** [comment]
This works well, thank you @arastasci
