### ISSUE TITLE
Frontend: Quiz Review

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#793]
## Issue Description
Users should be able to review their solved quizzes and see what they did right or wrong.

## Tasks
- [x] Show correct and wrong answers in questions
- [x] Show correct and wrong answers in compact question navigation 

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 14/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 15/12/2024 - 23:59

**Comment by Elifnurdeniz** [comment]
It is done in [here ](https://github.com/bounswe/bounswe2024group6/pull/796) @yunusemreozdemir .
