### ISSUE TITLE
Backend: Admins can only delete their own comments

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#794]
## Issue Description
Right now, the implementation in the BACKEND-DEV branch has an error. When an admin tries to delete the comment of anyone other than himself, the endpoint returns a 404 response. This should be fixed and admins should be able to delete the comments of anyone.

## Tasks

- [ ] Let admins delete the comments of anyone using the platform in the backend.

## Estimated Time

**Estimated Time:** 5 minutes

## Deadline

**Deadline:** 13/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 14/12/2024 - 23:59

**Comment by arastasci** [comment]
LGTM, i forgor that 💀
