### ISSUE TITLE
revising labels

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#8]
After creating some issues, I thought that labels such as `question`, `research` and `planning` could be useful and we discussed it at WhatsApp shortly, and decided we will be adding them. If there are other labels that you think might be good, please share and we can discuss.

**Comment by Elifnurdeniz** [comment]
Maybe 'coding' label can be added.

**Comment by battal255** [comment]
We added 'coding' label. The labels seem sufficient for now.
