### ISSUE TITLE
Backend: Additional Activity Streams 

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#814]
## Issue Description

We shall implement activity streams notifications for quizzes, notifications are as follows:

* **X** solved your **quiz**!
* **X** created a **quiz**! (Only if Y follows X)
* **X** deleted your quiz, _QuizName_!
* **X** liked your **quiz**!
* **X** liked your **post**!
* **X** liked your **comment**!
* **X** created a **post**! (Only if Y follows X)
* **X** created a **comment**! (Only if Y follows X and the post the comment is under does not belong to Y)
* **X** commented on your **post**!
* **X** deleted your comment, _CommentText_!
* **X** deleted your post, _PostTitle_!
* **X** followed **You**!
* **X** unfollowed **You**!
* **X** was banned! (Only if Y follows X)
* **X** changed the tags of your **quiz**!
* **X** changed the tags of your **post**! 

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 14/12/2024 23.59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 15/12/2024 11.59

**Comment by YavizGuldalf** [comment]
Closing this issue as it's been completed with the merged PR (#835).
