### ISSUE TITLE
Research and Choose a UI Component Library

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#83]
We need to find a UI component library that preferably fits the following conditions:
- Can be used in both React and React Native
- Has the essential components we might use in our application
- Used extensively
- Compatible with TS and Tailwind CSS
- Open source
- Has light/dark themes

**Comment by Elifnurdeniz** [comment]
We discussed the libraries that I've found and decided on them in [meeting 11](https://github.com/bounswe/bounswe2024group6/wiki/Meeting-11). We chose shadcn ui for web, nativecn ui for mobile side.

**Comment by yunusemreozdemir** [comment]
Great work Elif.
