### ISSUE TITLE
Backend: Update Quiz Activity Stream

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#834]
## Issue Description

We should implement a notification stream for the "update quiz tags" activity.

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 15/12/2024 18.59

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 15/12/2024 23.59

**Comment by kaanyolcu22** [comment]
@YavizGuldalf I have fixed it you can close the issue .

**Comment by YavizGuldalf** [comment]
Okay, it seems to be working well. Thank you.
