### ISSUE TITLE
Implement Shadcn UI

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#87]
Implement Shadcn UI to the project to be used as a component library in front-end side.

**Comment by Elifnurdeniz** [comment]
I've done the implementation and requested a pull request [here](https://github.com/bounswe/bounswe2024group6/pull/89). Can you check and close the issue @yunusemreozdemir?

**Comment by yunusemreozdemir** [comment]
Great work, closing.
