### ISSUE TITLE
Resarch and Practice SPARQL Language and Wikidata

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#93]
The SPARQL language should be understood before implementing behind structure of the first simple search .

**Comment by arastasci** [comment]
We studied SPARQL  from the following resources:
- [1](https://www.youtube.com/watch?v=FvGndkpa4K0)
- [2](https://www.youtube.com/watch?v=YC6jyl4hAxQ)

We also found a good site to create powerful queries for WikiData and learned from the examples in there:
- [Query builder](https://query.wikidata.org/querybuilder/?uselang=en)
- [Examples](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples)
