### ISSUE TITLE
Populate the Database with +100 posts

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#930]
## Issue Description
 For Customer Milestone 3 we need to populate the database for 100 posts . In order to that we need a script . 

## Estimated Time

**Estimated Time:** 1 hours

## Deadline

**Deadline:** 16/12/2024-18:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir @arastasci 
**Review Deadline:** 6/12/2024-20:00

**Comment by arastasci** [comment]
after careful consideration, we didn't take an action towards this. but thanks for the effort, @kaanyolcu22!
