### ISSUE TITLE
BACKEND: Unit Tests for Search Endpoint

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#978]
## Issue Description
 Writing Unit tests is needed for searching endpoints 

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 16/12/2024-21:30
## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 16/12/2024-22:00

**Comment by arastasci** [comment]
👏 LGTM
